[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.0.0"


[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"
